fithub/posts/forms.py
# Post form
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

fithub/main/routes.py
########################################################
# Routes for Fithub, and backend functions/methods. #
#                                                      #                                #
########################################################

import os
import operator
import secrets

from datetime import datetime
from urllib.parse import urlparse
from PIL import Image

import flask

from flask import render_template, url_for, flash, redirect, request, abort,Blueprint, current_app
from fithub import db, bcrypt, mail
from fithub.main.forms import MacroForm, MealForm
from fithub.models import User, Profile, Schedule, Exercise, Macros, Meal, Post
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message

main = Blueprint('main',__name__)

# Route to the homepage.
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5)
    return render_template('home.html', posts=posts)


# Route to the main Fithub exercises database.
@main.route("/workouts/database")
@login_required
def exercise_db():
    today = datetime.today().strftime("%A")


    return render_template('exercise-db.html', title = "Exercise Database", today = today)


# Route to the Fithub exercises database for leg workouts, page 1.
@main.route("/workouts/database/legs1")
@login_required
def exercise_db_legs1():
    today = datetime.today().strftime("%A")

    return render_template('exercise-db-legs1.html', title = "Exercise Database: Legs", today = today)


# Route to the Fithub exercises database for leg workouts, page 2.
@main.route("/workouts/database/legs2")
@login_required
def exercise_db_legs2():
    today = datetime.today().strftime("%A")

    return render_template('exercise-db-legs2.html', title = "Exercise Database: Legs", today = today)


### Routes and functions to do with the nutrition page. ###

"""Return an integer for the remaining macros for a selected day. The selected day has user-set MACROS numbers, 
   and TODAYS_MEALS contains the macros eaten so far today."""
def get_remaining_macros(macros, todays_meals):
    remaining_macros = [macros.protein - sum([x.protein for x in todays_meals]),
                        macros.carbs - sum([x.carbs for x in todays_meals]),
                        macros.fat - sum([x.fat for x in todays_meals]),
                        macros.calories - sum([x.calories for x in todays_meals])]

    return remaining_macros


# Route to the main nutrition page.
@main.route("/nutrition", methods = ['GET', 'POST'])
def nutrition():
    today = datetime.today()
    current_day = today.strftime("%A")

    if current_user.is_authenticated:
        macros = Macros.query.filter(Macros.user_id == current_user.id, Macros.day == current_day).first()
        meals = Meal.query.filter(Meal.user_id == current_user.id).all()
        todays_meals = [x for x in meals if x.time.strftime('%d-%m-%Y') == today.strftime('%d-%m-%Y')]

        remaining = get_remaining_macros(macros, todays_meals)

        return render_template('nutrition.html', title = 'Nutrition', macros = macros, remaining = remaining, meals = todays_meals,
            today = datetime.today())

    else:
        return render_template('nutrition.html', title = 'Nutrition', today = datetime.today())


# Route to a WTForms instance for setting or editing TODAY's macros (by datetime).
@main.route("/nutrition/set-macros/today", methods = ['GET', 'POST'])
@login_required
def set_macros():
    form = MacroForm()
    day = datetime.today().strftime("%A")

    if form.validate_on_submit():
        if form.set_all.data == True:
            macros = Macros.query.filter(Macros.user_id == current_user.id).all()

            calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

            for m in macros:
                m.protein = form.protein.data
                m.carbs = form.carbs.data
                m.fat = form.fat.data
                m.calories = calories

            db.session.commit()

        else:
            macros = Macros.query.filter(Macros.user_id == current_user.id, Macros.day == form.day.data).first()

            calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

            macros.protein = form.protein.data
            macros.carbs = form.carbs.data
            macros.fat = form.fat.data
            macros.calories = calories

            db.session.commit()

        flash("You have set your daily macros.", "success")

        return redirect(url_for('main.nutrition'))

    elif request.method == 'GET':
        form.day.data = day

    return render_template('set-macros.html', title = "Set Macros", form = form)


# Route to a WTForms instance for setting or editing any WEEKDAY's macros.
@main.route("/nutrition/set-macros/<weekday>", methods = ['GET', 'POST'])
@login_required
def set_macros2(weekday):
    form = MacroForm()
    day = datetime.today().strftime("%A")

    if form.validate_on_submit():
        if form.set_all.data == True:
            macros = Macros.query.filter(Macros.user_id == current_user.id).all()

            calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

            for m in macros:
                m.protein = form.protein.data
                m.carbs = form.carbs.data
                m.fat = form.fat.data
                m.calories = calories

            db.session.commit()

        else:
            macros = Macros.query.filter(Macros.user_id == current_user.id, Macros.day == form.day.data).first()

            calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

            macros.protein = form.protein.data
            macros.carbs = form.carbs.data
            macros.fat = form.fat.data
            macros.calories = calories

            db.session.commit()

        flash("You have set your daily macros.", "success")

        return redirect(url_for('main.view_macros'))

    elif request.method == 'GET':
        form.day.data = weekday

    return render_template('set-macros.html', title = "Set Macros", form = form)


# Route to a webpage that displays the macros for all 7 days of the week.
@main.route("/nutrition/view-macros")
@login_required
def view_macros():
    macros = Macros.query.filter(Macros.user_id == current_user.id).all()

    return render_template('view-macros.html', title = "View Macros", macros = macros)


# Route to a WTForms instance for adding a new meal, where the previous page was .
@main.route("/nutrition/new-meal", methods = ['GET', 'POST'])
@login_required
def new_meal1():
    form = MealForm()

    if form.validate_on_submit():
        calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

        meal = Meal(description = form.description.data, food_type = form.food_type.data, time = form.time.data, protein = form.protein.data,
            carbs = form.carbs.data, fat = form.fat.data, calories = calories, user_id = current_user.id)

        db.session.add(meal)
        db.session.commit()

        flash("You have successfully logged your meal.", "success")
        return redirect(url_for('main.nutrition'))

    return render_template('new-meal.html', title = "New Meal", form = form)


# Route to a WTForms instance for adding a new meal, where the previous page was .
@main.route("/nutrition/meal-log/new-meal", methods = ['GET', 'POST'])
@login_required
def new_meal2():
    form = MealForm()

    if form.validate_on_submit():
        calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

        meal = Meal(description = form.description.data, food_type = form.food_type.data, time = form.time.data, protein = form.protein.data,
            carbs = form.carbs.data, fat = form.fat.data, calories = calories, user_id = current_user.id)

        db.session.add(meal)
        db.session.commit()

        flash("You have successfully logged your meal.", "success")
        return redirect(url_for('main.meal_log'))

    return render_template('new-meal.html', title = "New Meal", form = form)


# Route to the user's meal log, a webpage that contains data about all meals eaten today (by datetime).
@main.route("/nutrition/meal-log")
@login_required
def meal_log():
    today = datetime.today()

    meals = Meal.query.filter(Meal.user_id == current_user.id).all()
    todays_meals = [x for x in meals if x.time.strftime('%d-%m-%Y') == today.strftime('%d-%m-%Y')]

    sorted_meals = sorted(todays_meals, key = operator.attrgetter('calories'))

    return render_template('meal-log.html', title = "Meal Log", meals = todays_meals, sorted_meals = sorted_meals,
        today = datetime.today())


# Route to a WTForms instance for editing the data for a meal with MEAL_ID.
@main.route("/nutrition/meal-log/<int:meal_id>/update-meal", methods = ['GET', 'POST'])
@login_required
def update_meal(meal_id):
    meal = Meal.query.filter(Meal.user_id == current_user.id, Meal.id == meal_id).first()

    if meal.user != current_user:
        abort(403)

    form = MealForm()

    if form.validate_on_submit():
        meal.description = form.description.data
        meal.food_type = form.food_type.data
        meal.time = form.time.data
        meal.protein = form.protein.data
        meal.carbs = form.carbs.data
        meal.fat = form.fat.data

        meal.calories = 4*form.protein.data + 4*form.carbs.data + 9*form.fat.data

        db.session.commit()

        return redirect(url_for('main.meal_log'))

    elif request.method == 'GET':
        form.description.data = meal.description
        form.food_type.data = meal.food_type
        form.time.data = meal.time
        form.protein.data = meal.protein
        form.carbs.data = meal.carbs
        form.fat.data = meal.fat

    return render_template('update-meal.html', title = "Edit Your Meal", form = form)

fithub/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from fithub import db
from fithub.models import Post
from fithub.posts.forms import PostForm

posts = Blueprint('posts',__name__)

@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form =PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)#create Post object
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                            form=form, legend='New Post')

@posts.route("/post/<int:post_id>") #flask let us put variable in the route using<>
def post(post_id):
    post = Post.query.get_or_404(post_id) #get the blog with this id or get 404 error
    return render_template('post.html', title=post.title, post=post) #past variables to post.html


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post',post=post)

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.community'))

fithub/templates/account.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
      <div class="media">
      <a href="{{ url_for('users.change_profile_image') }}">
      	<img class="rounded-circle account-img" src="{{ image_file }}">
      </a>
      	<div class="media-body">
      		<h4 class="account-heading">{{ current_user.first_name }} {{ current_user.last_name }}</h4>
      		<p class="text-secondary">Username: {{ current_user.username }}</p>
      		<p class="text-secondary">Email: {{ current_user.email }}</p>
      		<p class="text-secondary">{{ current_user.profile[0].quote }}</p>
      		<p class="text-secondary">Joined {{ current_user.date_joined }}.</p>
      	</div>
      </div>
    </div>

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         <h3>{{ current_user.first_name }}'s Profile.</h3>
         <p class='text-muted'>Manage your account details here.
            <ul class="list-group">
              <a href="{{ url_for('users.change_user') }}" class="button5">
                <span>Change Your Username and Email</span></a>
              <a href="#" class="button5">
                <span>Change Account Details</span></a>
              <a href="{{ url_for('users.change_password') }}" class="button5">
                <span>Change Your Password</span></a>
              <a href="{{ url_for('users.physical_test') }}" class="button5">
                <span>Physical Test</span></a>
   
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}

fithub/templates/exercise-db-legs1.html
{% extends "layout.html" %}
{% block content %}
    {%  if current_user.is_authenticated %}

      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Leg and Lower Body Exercises</h4>
          </div>
          <ul>
            <li><p>Description.</p></li>
            <li><p>If you're curious about any description term or , visit our <a href="">Resources</a> page.</p></li>
            <li><p></p></li>
          </ul>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/squats.png') }}">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Barbell Squat</h4>
          </div>
          <ul>
            <li><p>Often called the "granddaddy of all exercises," the barbell squat is one of the "Big Three" that is an absolute necessity to any workout routine. This compound movement exercise </p></li>
            <li><p><strong>Exercise Type: </strong>Compound</p></li>
            <li><p><strong>Difficulty: </strong>Intermediate - Expert</p></li>
            <li><p><strong>Exercise Video: </strong><a href="https://www.youtube.com/watch?v=nEQQle9-0NA" target="_blank">
            YouTube Link</a></p></li>
            <li><a href="{{ url_for('users.add_exercise3', exercise_name = 'Squats', difficulty = 'Intermediate') }}">
              <p>Add this Exercise to One of My Workouts</p></a></li>
          </ul>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/legpress.png') }}">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Leg Press</h4>
          </div>
          <ul>
            <li><p>Description. Caution: Do NOT Lock Your Knees!</p></li>
            <li><p><strong>Exercise Type: </strong>Compound</p></li>
            <li><p><strong>Difficulty: </strong></p></li>
            <li><p><strong>Exercise Video: </strong><a href="https://www.youtube.com/watch?v=CHPHn-OnTqE" target="_blank">
            YouTube Link</a></p></li>
            <li><a href="{{ url_for('users.add_exercise3', exercise_name = 'Leg Press', difficulty = 'Beginner') }}">
              <p>Add this Exercise to One of My Workouts</p></a></li>
          </ul>
        </div>
      </article>


      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.exercise_db_legs1') }}">1</a>
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.exercise_db_legs2') }}">2</a>

    {% else %}

    <h2>Workout </h2>

    {% endif %}

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         {%  if current_user.is_authenticated %}
         <h3>{{ current_user.first_name }}'s Workouts.</h3>
         <p class='text-muted'>Description.
            <ul class="list-group">
              <a href="{{ url_for('users.workouts') }}" class="button3"><span>Today's Workout</span></a>
              <a href="{{ url_for('users.add_exercise1', today = today) }}" class="button3">
                <span>Add an Exercise</span></a>
              <a href="" class="button3">
                <span>Resources</span></a>
              <a href="{{ url_for('main.exercise_db') }}" class="button3">
                <span>Exercise Database</span></a>
         {% else %}
          <h3>Your Nutrition, Simplified.</h3>
          <p class='text-muted'>Easily log and track your nutritional data so you can maximize your workouts and ....
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
                <span>Set Macros</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
                <span>Resources</span></a>
          {% endif %}
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}

fithub/templates/exercise-db-legs2.html
{% extends "layout.html" %}
{% block content %}
    {%  if current_user.is_authenticated %}

      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Leg and Lower Body Exercises</h4>
          </div>
          <ul>
            <li><p>Description.</p></li>
            <li><p>If you're curious about any description term or , visit our <a href="">Resources</a> page.</p></li>
            <li><p></p></li>
          </ul>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/deadlift.png') }}">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Barbell Deadlift</h4>
          </div>
          <ul>
            <li><p>Descriptions:Deadlifting in itself is not dangerous – but like with any movement, deadlifting incorrectly can be. Properly executing the deadlift will allow you to build a stronger posterior chain, less fragile joints, and a body that can handle whatever life throws at you.</p></li>
            <li><p><strong>Exercise Type: </strong>Compound</p></li>
            <li><p><strong>Difficulty: </strong>Intermediate - Expert</p></li>
            <li><p><strong>Exercise Video: </strong><a href="https://www.youtube.com/watch?v=hCDzSR6bW10" target="_blank">
            YouTube Link</a></p></li>
            <li><a href="{{ url_for('users.add_exercise3', exercise_name = 'Deadlift', difficulty = 'Intermediate') }}">
              <p>Add this Exercise to One of My Workouts</p></a></li>
          </ul>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/Goblet squat.jpg') }}">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Goblet squat</h4>
          </div>
          <ul>
            <li><p>Description:Perform a goblet squat: When holding a dumbbell, one end touches the chest and one end touches the abdomen. When you are kneeling, you find that the lower end of the dumbbell is no longer in contact with the abdomen, which means the upper body is too forward.</p></li>
            <li><p><strong>Exercise Type: </strong>Compound</p></li>
            <li><p><strong>Difficulty: </strong></p></li>
            <li><p><strong>Exercise Video: </strong><a href="https://www.youtube.com/watch?v=zcJeHchdp9o" target="_blank">
            YouTube Link</a></p></li>
            <li><a href="{{ url_for('users.add_exercise3', exercise_name = 'Leg Press', difficulty = 'Beginner') }}">
              <p>Add this Exercise to One of My Workouts</p></a></li>
          </ul>
        </div>
      </article>


      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.exercise_db_legs1') }}">1</a>
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.exercise_db_legs2') }}">2</a>

    {% else %}

    <h2>Workout </h2>

    {% endif %}

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         {%  if current_user.is_authenticated %}
         <h3>{{ current_user.first_name }}'s Workouts.</h3>
         <p class='text-muted'>Description.
            <ul class="list-group">
              <a href="{{ url_for('users.workouts') }}" class="button3"><span>Today's Workout</span></a>
              <a href="{{ url_for('users.add_exercise1', today = today) }}" class="button3">
                <span>Add an Exercise</span></a>
              <a href="" class="button3">
                <span>Resources</span></a>
              <a href="{{ url_for('main.exercise_db') }}" class="button3">
                <span>Exercise Database</span></a>
         {% else %}
          <h3>Your Nutrition, Simplified.</h3>
          <p class='text-muted'>Easily log and track your nutritional data so you can maximize your workouts and ....
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
                <span>Set Macros</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
                <span>Resources</span></a>
          {% endif %}
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}

fithub/templates/exercise-db.html
{% extends "layout.html" %}
{% block content %}
    {%  if current_user.is_authenticated %}

      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Fit-hub Exercise Database</h4>
          </div>
          <ul>
            <li><p>Some Description.</p></li>
            <li><p>Click on one of the cards to view all exercises associated with that muscle group.</p></li>
            <li><p></p></li>
            <li><p></p></li>
          </ul>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/legs-db.jpg') }}">
        <div class="media-body">
          <div class="article-metadata">
            <a href="{{ url_for('main.exercise_db_legs1') }}"><h4>Legs and Lower Body</h4></a>
          </div>
          <ul>
            <li><p>A collection of lower body exercises, ... description.</p></li>
            <li><p></p></li>
            <li><p></p></li>
            <li><p></p></li>
          </ul>
        </div>
      </article>

    {% else %}

    <h2>Workout </h2>

    {% endif %}

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         {%  if current_user.is_authenticated %}
         <h3>{{ current_user.first_name }}'s Workouts.</h3>
         <p class='text-muted'>Description.
            <ul class="list-group">
              <a href="{{ url_for('users.workouts') }}" class="button3"><span>Today's Workout</span></a>
              <a href="{{ url_for('users.add_exercise1', today = today) }}" class="button3">
                <span>Add an Exercise</span></a>
              <a href="" class="button3">
                <span>Resources</span></a>
              <a href="" class="button3">
                <span>Exercise Database</span></a>
         {% else %}
          <h3>Your Nutrition, Simplified.</h3>
          <p class='text-muted'>Easily log and track your nutritional data so you can maximize your workouts and ....
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
                <span>Set Macros</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
                <span>Resources</span></a>
          {% endif %}
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}

fithub/templates/nutr-res.html
{% extends "layout.html" %}
{% block content %}
    {%  if current_user.is_authenticated %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h4>Understanding Your Nutrition</h4>
          </div>
          <p>It's often said that fitness comes down to 30% working out, and 70% diet. FILLER.</p>
          <p>Click on one of the cards to learn more about each topic.</p>
        </div>
      </article>

      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/macrochart.jpg') }}">
        <div class="media-body">
          <div class="article-metadata">
            <a href=""><h4>Macros 101 - Understanding the Building Blocks</h4></a>
          </div>
          <p>What are macronutrients, or "macros"? How does it make up everything I eat? How do I know how much of it I should eat? How should I adjust my macros to fit different eating and dieting techniques? FILLER.</p>
          <p>Learn everything you need to know about the very fundamentals of nutrition here.</p>
        </div>
      </article>



    {% else %}


{% endif %}

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         {%  if current_user.is_authenticated %}
         <h3>Resources for {{ current_user.first_name }}.</h3>
         <p class='text-muted'>Check out these articles and websites tailored to help you understand your nutrition better.
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
              	<span>Set Your Macros</span></a>
              <a href="{{ url_for('main.view_macros') }}" class="button3">
                <span>View Your Macros</span></a>
              <a href="{{ url_for('main.nutrition') }}" class="button3">
                <span>View Your Nutrition</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>View Your Meal Log</span></a>
         {% else %}
          <h3>Your Nutrition, Simplified.</h3>
          <p class='text-muted'>Easily log and track your nutritional data so you can maximize your workouts and ....
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
                <span>Set Macros</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
                <span>Resources</span></a>
          {% endif %}
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}

fithub/templates/view-macros.html
{% extends "layout.html" %}
{% block content %}
    {%  if current_user.is_authenticated %}

    {% for macro in macros %}
      <article class="media content-section">
        <!-- All images and logos used in this file are fully credited to http://www.flaticon.com. -->
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + macro.day + '.png') }}">
        <div class="media-body">
          <div class="article-metadata">
            <h4>{{ macro.day }}</h4>
          </div>
          {% if macro.protein == -1 %}
          <p>You have not set your macros for this day yet. Click <a href="{{ url_for('main.set_macros2', weekday = macro.day) }}">here</a> to set your macros for {{ macro.day }}.</p>
          {% else %}
          <ul>
            <li><strong>Protein:</strong> {{ macro.protein }}g</li>
            <li><strong>Carbs:</strong> {{ macro.carbs }}g</li>
            <li><strong>Fat:</strong> {{ macro.fat }}g</li>
            <li><strong>Calories:</strong> {{ macro.calories }} cal.</li>
          </ul>
          {% endif %}
          <small class="text-muted"><a href="{{ url_for('main.set_macros2', weekday = macro.day) }}">Edit {{ macro.day }}'s Macros</a></small>
        </div>
      </article>

    {% endfor %}

    {% else %}

    <h2>Error</h2>

{% endif %}

{% endblock content %}

{% block content1 %}

    <div class="col-md-4">
        <div class="content-section1">
         {%  if current_user.is_authenticated %}
         <h3>{{ current_user.first_name }}'s Macros.</h3>
         <p class='text-muted'>View, edit, and organize your macros for the week.
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
              	<span>Set Your Macros</span></a>
              <a href="{{ url_for('main.nutrition') }}" class="button3">
                <span>View Your Nutrition</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>View Your Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
              	<span>Resources</span></a>
         {% else %}
          <h3>Your Nutrition, Simplified.</h3>
          <p class='text-muted'>Easily log and track your nutritional data so you can maximize your workouts and ....
            <ul class="list-group">
              <a href="{{ url_for('main.set_macros') }}" class="button3">
                <span>Set Macros</span></a>
              <a href="{{ url_for('main.new_meal1') }}" class="button3">
                <span>Add a Meal</span></a>
              <a href="{{ url_for('main.meal_log') }}" class="button3">
                <span>Meal Log</span></a>
              <a href="{{ url_for('main.nutrition_resources') }}" class="button3">
                <span>Resources</span></a>
          {% endif %}
            </ul>
         </p>
        </div>
    </div>

{% endblock content1 %}